spring:
  application:
    name: lms

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    url: jdbc:mysql://127.0.0.1:3308/lms_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lms_user
    password: LmsUser!2026#
    driver-class-name: com.mysql.cj.jdbc.Driver


  mail:
    host: smtp.gmail.com
    port: 587
    username: speed6569@gmail.com
    password: "vwmz dsgm qgnz pzbb"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from: speed6569@gmail.com

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.security: INFO
